# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowCircle.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowCircle(object):
    def setupUi(self, WindowCircle):
        WindowCircle.setObjectName("WindowCircle")
        WindowCircle.resize(300, 220)
        WindowCircle.setMaximumSize(QtCore.QSize(300, 220))
        self.layoutWidget = QtWidgets.QWidget(WindowCircle)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 309, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_r = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_r.setMaximumSize(QtCore.QSize(80, 20))
        self.lineEdit_r.setObjectName("lineEdit_r")
        self.gridLayout.addWidget(self.lineEdit_r, 3, 2, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start.setMaximumSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 0, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear.setMaximumSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lineEdit_y = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_y.setMaximumSize(QtCore.QSize(80, 20))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.gridLayout.addWidget(self.lineEdit_y, 2, 2, 1, 1)
        self.lineEdit_x = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_x.setMaximumSize(QtCore.QSize(80, 20))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.gridLayout.addWidget(self.lineEdit_x, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.pushButton_return = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_return.setMaximumSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.pushButton_return.setFont(font)
        self.pushButton_return.setObjectName("pushButton_return")
        self.gridLayout.addWidget(self.pushButton_return, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(82, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(WindowCircle)
        QtCore.QMetaObject.connectSlotsByName(WindowCircle)

    def retranslateUi(self, WindowCircle):
        _translate = QtCore.QCoreApplication.translate
        WindowCircle.setWindowTitle(_translate("WindowCircle", "中点圆"))
        self.pushButton_start.setText(_translate("WindowCircle", "开始绘制"))
        self.pushButton_clear.setText(_translate("WindowCircle", "清空绘图"))
        self.label_3.setText(_translate("WindowCircle", "y"))
        self.label_2.setText(_translate("WindowCircle", "x"))
        self.label_4.setText(_translate("WindowCircle", "圆心"))
        self.label_6.setText(_translate("WindowCircle", "r"))
        self.label_5.setText(_translate("WindowCircle", "半径"))
        self.pushButton_return.setText(_translate("WindowCircle", "返回"))
        self.label.setText(_translate("WindowCircle", "请输入坐标"))
